# -*- coding: utf-8 -*-
"""fastapi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCJtAvIxsyjPc-uJUisSudbrWQgqSV_w
"""

from fastapi import FastAPI, HTTPException, Query, Response
from pydantic import BaseModel
from typing import Optional
from fastapi import status

app = FastAPI()

class NewProduct(BaseModel):
    name: str
    price: float
    category: str
    in_stock: bool = True

products = [
    {"id": 1, "name": "Wireless Mouse", "price": 499, "category": "Electronics", "in_stock": True},
    {"id": 2, "name": "USB Cable", "price": 99, "category": "Electronics", "in_stock": True},
    {"id": 3, "name": "USB Hub", "price": 799, "category": "Electronics", "in_stock": False},
    {"id": 4, "name": "Pen Set", "price": 49, "category": "Stationery", "in_stock": True},
]

def find_product(product_id: int):
    for product in products:
        if product['id'] == product_id:
            return product
    return None

# Q1: POST endpoint to add new products
@app.post('/products', status_code=status.HTTP_201_CREATED)
def add_product(new_product: NewProduct):
    for product in products:
        if product['name'].lower() == new_product.name.lower():
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Product '{new_product.name}' already exists"
            )

    next_id = max(p['id'] for p in products) + 1
    new_product_dict = {
        "id": next_id,
        "name": new_product.name,
        "price": new_product.price,
        "category": new_product.category,
        "in_stock": new_product.in_stock
    }
    products.append(new_product_dict)
    return {"message": "Product added", "product": new_product_dict}

# Q2: PUT endpoint to update product
@app.put('/products/{product_id}')
def update_product(product_id: int, price: Optional[float] = None, in_stock: Optional[bool] = None):
    product = find_product(product_id)
    if not product:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")

    if price is not None:
        product['price'] = price
    if in_stock is not None:
        product['in_stock'] = in_stock

    return {"message": "Product updated", "product": product}

# Q3: DELETE endpoint to remove product
@app.delete('/products/{product_id}')
def delete_product(product_id: int, response: Response):
    product = find_product(product_id)
    if not product:
        response.status_code = status.HTTP_404_NOT_FOUND
        return {"error": "Product not found"}

    products.remove(product)
    return {"message": f"Product '{product['name']}' deleted"}

# Q5: GET /products/audit endpoint (MUST BE ABOVE GET /products/{product_id})
@app.get('/products/audit')
def product_audit():
    in_stock_list = [p for p in products if p['in_stock']]
    out_stock_list = [p for p in products if not p['in_stock']]
    stock_value = sum(p['price'] * 10 for p in in_stock_list)
    priciest = max(products, key=lambda p: p['price'])

    return {
        "total_products": len(products),
        "in_stock_count": len(in_stock_list),
        "out_of_stock_names": [p['name'] for p in out_stock_list],
        "total_stock_value": stock_value,
        "most_expensive": {"name": priciest['name'], "price": priciest['price']}
    }

# Bonus: PUT /products/discount endpoint (MUST BE ABOVE GET /products/{product_id})
@app.put('/products/discount')
def bulk_discount(
    category: str = Query(..., description='Category to discount'),
    discount_percent: int = Query(..., ge=1, le=99, description='% off')
):
    updated = []
    for p in products:
        if p['category'] == category:
            p['price'] = int(p['price'] * (1 - discount_percent / 100))
            updated.append(p)

    if not updated:
        return {"message": f"No products found in category: {category}"}

    return {
        "message": f"{discount_percent}% discount applied to {category}",
        "updated_count": len(updated),
        "updated_products": updated
    }

# GET all products
@app.get('/products')
def get_products():
    return {"products": products, "total": len(products)}

# GET single product by ID
@app.get('/products/{product_id}')
def get_product(product_id: int):
    product = find_product(product_id)
    if not product:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")
    return product