# -*- coding: utf-8 -*-
"""Feb Internship 2026 Function .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O51aeY8SU2jVNv9wYwIHC6GJhwxEB0mE
"""

def smart_parking(capacity, logs):
    current = 0
    peak = 0

    for log in logs:
        if log == "IN":
            current += 1
        elif log == "OUT":
            current -= 1

        if current > peak:
            peak = current

    print("Currently Parked Vehicles:", current)

    if current > capacity:
        print("Parking Status: Full - Alert!")
    else:
        print("Parking Status: Available")

    print("Peak Parking Usage:", peak)

# Sample Input
smart_parking(50, ["IN", "IN", "IN", "OUT", "IN", "IN", "OUT"])

def delivery_eta(distance, traffic, weather):
    base_time = distance * 5   # 5 minutes per km

    # Traffic adjustment
    if traffic == "High":
        base_time += 15
    elif traffic == "Medium":
        base_time += 8

    # Weather adjustment
    if weather == "Rainy":
        base_time += 10
    elif weather == "Storm":
        base_time += 20

    print("Estimated Delivery Time:", base_time, "minutes")

# Sample Input
delivery_eta(8, "High", "Rainy")

def theatre_occupancy(total_seats, booked_seats):
    booked = len(booked_seats)
    occupancy = (booked / total_seats) * 100

    print("Occupancy:", str(int(occupancy)) + "%")

    if occupancy == 100:
        print("Show Status: Housefull")
    elif occupancy >= 75:
        print("Show Status: Almost Full")
        print("Suggestion: Consider opening additional show")
    else:
        print("Show Status: Seats Available")

# Sample Input
theatre_occupancy(200, [1]*150)

def server_load(cpu_readings):
    avg = sum(cpu_readings) / len(cpu_readings)

    print("Average CPU Load:", str(int(avg)) + "%")

    if avg < 50:
        print("Server Status: Normal")
    elif 50 <= avg <= 80:
        print("Server Status: Warning")
    else:
        print("Server Status: Critical")

# Sample Input
server_load([45, 60, 70, 85, 90])

def classroom_monitor(resources):
    overused = []

    for resource, hours in resources.items():
        if hours > 8:   # Threshold
            overused.append(resource)

    if overused:
        print("Overused Resources:", ", ".join(overused))
        print("Energy Alert: Yes")
    else:
        print("Overused Resources: None")
        print("Energy Alert: No")

# Sample Input
classroom_monitor({
    "Projector": 6,
    "AC": 9,
    "Lights": 4
})

def event_registration(capacity, registrations):
    if registrations > capacity:
        confirmed = capacity
        waitlisted = registrations - capacity
        status = "Closed"
    else:
        confirmed = registrations
        waitlisted = 0
        status = "Open"

    print("Confirmed Registrations:", confirmed)
    print("Waitlisted Users:", waitlisted)
    print("Registration Status:", status)

# Sample Input
event_registration(100, 105)