# -*- coding: utf-8 -*-
"""Smart_Parking_Lot_Management

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlNjzlmYwy8T0_l7mX6fiWPO95K3BfDu
"""

# Smart Parking Lot Management System

def manage_parking(capacity, logs):
    """
    Manages a smart parking lot system.

    Parameters:
    capacity (int): Maximum parking capacity
    logs (list): List of vehicle entry/exit logs ("IN" or "OUT")

    Returns:
    dict: Contains currently parked vehicles and parking status
    """

    # Initialize variables
    current_parked = 0
    peak_usage = 0
    parking_exceeded = False

    # Process each log entry
    for log in logs:
        if log == "IN":
            current_parked += 1
            # Update peak usage if current parked exceeds it
            if current_parked > peak_usage:
                peak_usage = current_parked
            # Check if parking exceeds capacity
            if current_parked > capacity:
                parking_exceeded = True
        elif log == "OUT":
            current_parked -= 1

    # Determine parking status
    if parking_exceeded:
        status = "Full - Capacity Exceeded"
    elif current_parked >= (capacity * 0.8):  # 80% capacity
        status = "Almost Full"
    elif current_parked > 0:
        status = "Available"
    else:
        status = "Empty"

    # Return results
    return {
        "Currently Parked Vehicles": current_parked,
        "Peak Parking Usage": peak_usage,
        "Parking Status": status,
        "Capacity Exceeded": parking_exceeded
    }

# Test with the provided sample input
parking_capacity = 50
vehicle_logs = ["IN", "IN", "IN", "OUT", "IN", "IN", "OUT"]

result = manage_parking(parking_capacity, vehicle_logs)
print("Test Case 1:")
print(f"Parking Capacity: {parking_capacity}")
print(f"Vehicle Logs: {vehicle_logs}")
print(f"\nOutput:")
print(f"Currently Parked Vehicles: {result['Currently Parked Vehicles']}")
print(f"Peak Parking Usage: {result['Peak Parking Usage']}")
print(f"Parking Status: {result['Parking Status']}")
print(f"Capacity Exceeded: {result['Capacity Exceeded']}")

# Additional test cases
print("\n" + "="*50)
print("\nTest Case 2: Over Capacity")
parking_capacity_2 = 3
vehicle_logs_2 = ["IN", "IN", "IN", "IN", "OUT"]
result_2 = manage_parking(parking_capacity_2, vehicle_logs_2)
print(f"Parking Capacity: {parking_capacity_2}")
print(f"Vehicle Logs: {vehicle_logs_2}")
print(f"\nOutput:")
print(f"Currently Parked Vehicles: {result_2['Currently Parked Vehicles']}")
print(f"Peak Parking Usage: {result_2['Peak Parking Usage']}")
print(f"Parking Status: {result_2['Parking Status']}")
print(f"Capacity Exceeded: {result_2['Capacity Exceeded']}")

# ===== PROBLEM 2: Online Food Delivery Time Estimator =====

def estimate_delivery_time(distance, traffic_level, weather):
    """
    Estimates delivery time based on distance, traffic, and weather.

    Parameters:
    distance (float): Distance in kilometers
    traffic_level (str): 'Low', 'Medium', 'High'
    weather (str): 'Clear', 'Rainy', 'Stormy'

    Returns:
    dict: Contains estimated delivery time and status
    """

    # Base delivery time: 5 minutes + 5 minutes per km
    base_time = 5 + (distance * 5)

    # Traffic delays
    traffic_multiplier = 1.0
    if traffic_level == "Low":
        traffic_multiplier = 1.0
    elif traffic_level == "Medium":
        traffic_multiplier = 1.25
    elif traffic_level == "High":
        traffic_multiplier = 1.5

    # Weather delays
    weather_delay = 0
    if weather == "Clear":
        weather_delay = 0
    elif weather == "Rainy":
        weather_delay = 10
    elif weather == "Stormy":
        weather_delay = 20

    # Calculate final time
    final_time = int(base_time * traffic_multiplier + weather_delay)

    return {
        "Estimated Delivery Time": f"{final_time} minutes",
        "Distance": f"{distance} km",
        "Traffic Impact": traffic_level,
        "Weather Impact": weather
    }

# Test Problem 2
print("\n" + "="*60)
print("PROBLEM 2: Online Food Delivery Time Estimator")
print("="*60)
distance = 8
traffic = "High"
weather = "Rainy"
result = estimate_delivery_time(distance, traffic, weather)
print(f"Distance: {distance} km")
print(f"Traffic Level: {traffic}")
print(f"Weather: {weather}")
print(f"\nEstimated Delivery Time: {result['Estimated Delivery Time']}")

# ===== PROBLEM 3: Movie Theatre Seat Occupancy Analyzer =====

def analyze_theatre_occupancy(total_seats, booked_seats):
    """
    Analyzes theatre seat booking data.

    Parameters:
    total_seats (int): Total seats in theatre
    booked_seats (list): List of booked seat indicators (1 = booked, 0 = empty)

    Returns:
    dict: Contains occupancy percentage and show status
    """

    # Count booked seats
    booked_count = sum(booked_seats)

    # Calculate occupancy percentage
    occupancy_percentage = (booked_count / total_seats) * 100

    # Determine show status
    if occupancy_percentage >= 100:
        status = "Housefull"
    elif occupancy_percentage >= 80:
        status = "Almost Full"
    elif occupancy_percentage >= 50:
        status = "Half Occupied"
    else:
        status = "Available"

    # Suggest additional shows
    suggest_new_show = occupancy_percentage >= 75

    return {
        "Occupancy": f"{occupancy_percentage:.0f}%",
        "Show Status": status,
        "Booked Seats": booked_count,
        "Available Seats": total_seats - booked_count,
        "Suggest New Show": suggest_new_show
    }

# Test Problem 3
print("\n" + "="*60)
print("PROBLEM 3: Movie Theatre Seat Occupancy Analyzer")
print("="*60)
total_seats = 200
booked_seats = [1] * 150 + [0] * 50  # 150 booked, 50 empty
result = analyze_theatre_occupancy(total_seats, booked_seats)
print(f"Total Seats: {total_seats}")
print(f"Booked Seats: {result['Booked Seats']}")
print(f"\nOccupancy: {result['Occupancy']}")
print(f"Show Status: {result['Show Status']}")
print(f"Suggest New Show: {result['Suggest New Show']}")

# ===== PROBLEM 4: Cloud Server Load Classification System =====

def classify_server_load(cpu_readings):
    """
    Classifies server load based on CPU usage readings.

    Parameters:
    cpu_readings (list): List of CPU usage percentages

    Returns:
    dict: Contains average CPU load and server status
    """

    # Calculate average CPU load
    avg_cpu = sum(cpu_readings) / len(cpu_readings)

    # Classify based on rules
    if avg_cpu < 50:
        status = "Normal"
    elif avg_cpu <= 80:
        status = "Warning"
    else:
        status = "Critical"

    return {
        "Average CPU Load": f"{avg_cpu:.0f}%",
        "Server Status": status,
        "Readings": cpu_readings,
        "Max Load": f"{max(cpu_readings)}%",
        "Min Load": f"{min(cpu_readings)}%"
    }

# Test Problem 4
print("\n" + "="*60)
print("PROBLEM 4: Cloud Server Load Classification System")
print("="*60)
cpu_readings = [45, 60, 70, 85, 90]
result = classify_server_load(cpu_readings)
print(f"CPU Readings (%): {result['Readings']}")
print(f"\nAverage CPU Load: {result['Average CPU Load']}")
print(f"Server Status: {result['Server Status']}")
print(f"Max Load: {result['Max Load']}")
print(f"Min Load: {result['Min Load']}")

# ===== PROBLEM 5: Smart Classroom Resource Usage Monitor =====

def monitor_classroom_resources(resource_usage):
    """
    Tracks classroom resource usage and identifies overuse patterns.

    Parameters:
    resource_usage (dict): Dictionary with resource names and usage hours

    Returns:
    dict: Contains overused resources and energy alert status
    """

    # Define resource limits (in hours)
    resource_limits = {
        "Projector": 6,
        "AC": 8,
        "Lights": 5
    }

    # Find overused resources
    overused_resources = []
    total_overuse = 0

    for resource, usage in resource_usage.items():
        limit = resource_limits.get(resource, 0)
        if usage > limit:
            overused_resources.append(resource)
            total_overuse += (usage - limit)

    # Determine energy alert
    energy_alert = "Yes" if total_overuse > 2 else "No"

    return {
        "Overused Resources": overused_resources if overused_resources else "None",
        "Energy Alert": energy_alert,
        "Total Overuse Hours": total_overuse,
        "Resource Usage": resource_usage
    }

# Test Problem 5
print("\n" + "="*60)
print("PROBLEM 5: Smart Classroom Resource Usage Monitor")
print("="*60)
resource_usage = {"Projector": 6, "AC": 9, "Lights": 4}
result = monitor_classroom_resources(resource_usage)
print(f"Resource Usage (hours): {result['Resource Usage']}")
print(f"\nOverused Resources: {result['Overused Resources']}")
print(f"Energy Alert: {result['Energy Alert']}")

# ===== PROBLEM 6: Online Event Registration Capacity Controller =====

def manage_event_registrations(capacity, registrations):
    """
    Manages event registrations and handles overbooking.

    Parameters:
    capacity (int): Maximum event capacity
    registrations (int): Total number of registrations

    Returns:
    dict: Contains confirmed registrations, waitlisted users, and status
    """

    # Calculate confirmed and waitlisted registrations
    confirmed_registrations = min(capacity, registrations)
    waitlisted_users = max(0, registrations - capacity)

    # Determine registration status
    if registrations > capacity:
        status = "Closed"
    elif registrations == capacity:
        status = "Full"
    else:
        status = "Open"

    return {
        "Confirmed Registrations": confirmed_registrations,
        "Waitlisted Users": waitlisted_users,
        "Registration Status": status,
        "Event Capacity": capacity,
        "Total Registrations": registrations
    }

# Test Problem 6
print("\n" + "="*60)
print("PROBLEM 6: Online Event Registration Capacity Controller")
print("="*60)
event_capacity = 100
total_registrations = 105
result = manage_event_registrations(event_capacity, total_registrations)
print(f"Event Capacity: {result['Event Capacity']}")
print(f"Total Registrations: {result['Total Registrations']}")
print(f"\nConfirmed Registrations: {result['Confirmed Registrations']}")
print(f"Waitlisted Users: {result['Waitlisted Users']}")
print(f"Registration Status: {result['Registration Status']}")

print("\n" + "="*60)
print("\n✓ All 6 problems have been solved successfully!")
print("="*60)